name: geothermal_osr
channels:
  - defaults
dependencies:
  - jupyter=1.0.0 
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pandas=1.0.2
  - pip=20.0.2
  - python=3.7
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - tensorflow=2.2.0
  - xlrd=1.2.0
